config/routes.rb
Rails.application.routes.draw do
  resources :post_attachments
  devise_for :users
  root 'categories#index'
  # get '*unmatched_route', to: 'application#not_found'

  resources :categories, only: [:index, :show] do
    resources :realties, only: [:index, :show]
  end
end

app/models/realty.rb
class Realty < ApplicationRecord
  validates :title, presence: true, uniqueness: { case_sensitive: false }

  before_destroy :remove_photos_from_folder

  belongs_to :user
  belongs_to :category
  has_many :post_attachments, dependent: :destroy

  accepts_nested_attributes_for :post_attachments

  scope :parser, -> { where('remote_id IS NOT NULL') }

  private

  def remove_photos_from_folder
    FileUtils.rm_rf("app/assets/images/diesel/#{self.remote_id}") if File.directory?("app/assets/images/diesel/#{self.remote_id}")
  end
end

app/controllers/realties_controller.rb
class RealtiesController < ApplicationController
  before_action :set_realty, only: [:show, :edit, :update, :destroy]

  def index
    @realties = Realty.parser.where(category_id: params[:category_id]).paginate(page: params[:page], :per_page => 10)
    # @realties = Realty.parser.all.paginate(page: params[:page])
  end

  def show
    if @realty
      @post_attachments = @realty.post_attachments.all
    else
      render 'not_found'
    end
  end

  # def cat
  #   case request.fullpath
  #   when "/realties/sale/1room"
  #     category_id = [1]
  #   when "/realties/sale/2room"
  #     category_id = [2]
  #   when "/realties/sale/3room"
  #     category_id = [3]
  #   when "/realties/sale"
  #     category_id = [1,2,3]
  #   else
  #     render 'not_found'
  #   end
  #   @realties = Realty.parser.where(category_id: category_id).paginate(page: params[:page], :per_page => 10)
  #   render 'index'
  # end

  def render_404
    render file: "#{Rails.root}/public/404", status: :not_found
  end


  # def new
  #   @realty = Realty.new
  #   @post_attachment = @realty.post_attachments.build
  # end

  # def edit
  #   @post_attachment = @realty.post_attachments.build
  # end

  # def create
  #   @realty = Realty.new(realty_params)
  #   @realty.user_id = current_user.id
  #   respond_to do |format|
  #     if @realty.save
  #       params[:post_attachments]['avatar'].each do |a|
  #         @post_attachment = @realty.post_attachments.create!(:avatar => a, :realty_id => @realty.id)
  #       end
  #       format.html { redirect_to @realty, notice: 'Realty was successfully created.' }
  #       format.json { render :show, status: :created, location: @realty }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @realty.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def update
  #   respond_to do |format|
  #     if @realty.update(realty_params)
  #       if params[:post_attachments].present?
  #         params[:post_attachments]['avatar'].each do |a|
  #           @post_attachment = @realty.post_attachments.create!(:avatar => a, :realty_id => @realty.id)
  #         end
  #       end
  #
  #       format.html { redirect_to @realty, notice: 'Realty was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @realty }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @realty.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @realty.destroy
  #   respond_to do |format|
  #     format.html { redirect_to realties_url, notice: 'Realty was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    def set_realty
      @realty = Realty.find_by(remote_id: params[:id])
    end

    def realty_params
      params.require(:realty).permit(:title, :remote_id, :category_id, :content, :user_id, post_attachments_attributes: [:id, :realty_id, :avatar])
    end
end

app/helpers/realties_helper.rb
module RealtiesHelper
  def get_photo_path(post)
    @realty.remote_id.present? ? "diesel/#{@realty.remote_id}/#{post.path}.png" : post.avatar
  end
end

app/views/realties/_form.html.erb
<%= form_with(model: realty, local: true) do |f| %>
  <% if realty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(realty.errors.count, "error") %> prohibited this realty from being saved:</h2>

      <ul>
      <% realty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :realty_title %>
  </div>

  <div class="field">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name, id: :realty_category_id %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, id: :realty_content %>
  </div>

  <%= f.fields_for :post_attachments do |p| %>
    <div class="field">
      <%= p.label :avatar %><br>
      <%= p.file_field :avatar, :multiple => true, name:     "post_attachments[avatar][]" %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/realties/cat.html.erb
роутинг, епта
<%= @a %>

app/views/realties/edit.html.erb
<h1>Editing Realty</h1>

<%= render 'form', realty: @realty %>

<%= link_to 'Show', @realty %> |
<%= link_to 'Back', realties_path %>

app/views/realties/index.html.erb
<% provide(:title, "#{@title} в Бишкеке") %>

<p id="notice"><%= notice %></p>

<h1><%= @title %> в Бишкеке</h1>


<% @realties.each do |realty| %>
  <table class="table table-striped">
    <tr>
      <td colspan="2"><%= link_to "#{realty.title}", "/categories/#{realty.category_id}/realties/#{realty.remote_id}" %> | <%= realty.category.name %></td>
    </tr>

    <tr>
      <td>
        <% if realty.post_attachments.present? %>
          <div>
            <%= image_tag("diesel/#{realty.remote_id}/#{realty.post_attachments.first.path}.png", alt: "#{realty.title}", style: "width:150px; height:150px;") %>
            Всего фото: <%= realty.post_attachments.count %>
          </div>
        <% end %>

      </td>


      <td><%= realty.content %></td>
    </tr>
  </table>
<% end %>


<%= will_paginate @realties %>

app/views/realties/new.html.erb
<h1>New Realty</h1>

<%= render 'form', realty: @realty %>

<%= link_to 'Back', realties_path %>

app/views/realties/not_found.html.erb
Данное объявление более не актуально

app/views/realties/show.html.erb
<% provide(:title, "#{@realty.title} - #{@realty.category.name} в Бишкеке") %>
<p id="notice"><%= notice %></p>

<h1>
  <%= @realty.title %>
</h1>

<p>
  <strong>Категория:<%= @realty.category.name %></strong>

</p>

<p>
  <%= @realty.content %>
</p>
<% @post_attachments.each do |post| %>
  <%= image_tag(get_photo_path(post), alt: 'Image') %>
<% end %>